### ISSUE TITLE
Nothing seems to work

### ISSUE THREAD

**Issue by knutwalker** [huhu/query.rs#11]
Hey, sorry for the vague description, but I can't seem to get any search working.

after typing in search bar, neither hitting return or clicking the search icon does anything, I don't get any results (nothing is happening at all, no suggestions open, no SERP, no redirects). Opening a URL like https://query.rs/?q=vec also does not initiate a search (and doesn't fill in the search box). Browser console does not show any errors when I try to submit a search, however I do get two errors when the site is loaded initially:

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'chrome.storage.local')
	(anonymous function) (0.CDA7PJTA.js:3:3500)
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'chrome.storage.local')
	(anonymous function) (2.DdXzupBa.js:2570:1112)
```

I'm using Orion on macOS, which is built on WebKit (`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15"`) but it _does_ work on Safari.

I also tried to disable all content/tracker/ad blockers and extensions and tried with the compatibility mode enabled, but nothing helped.

**Comment by knutwalker** [comment]
probably the same issue as #10

**Comment by Folyd** [comment]
Resolved via commit https://github.com/huhu/query.rs/commit/7b156186b36b64dbfcd745264e50470771efff81
