### ISSUE TITLE
search from URL

### ISSUE THREAD

**Issue by ear7h** [huhu/query.rs#5]
Hi, thank you for making this!

I was wondering if there's a way to make a search query by building a URL like `query.rs?q=u32`. I'd like to add this site as a [keyword search bookmark](https://www.reddit.com/r/firefox/comments/o3yfeo/just_discovered_firefox_bookmark_keywords_you_can/) in firefox (I tried finding official documentation for this to no avail), which builds a URL with a search query. The way I usually set this up is right clicking on a search box, but I think it involves a button element with attribute `type="search"`, **and** a submittable form? Which doesn't seem to apply here since the search is all local?

Btw I really appreciate the local-first approach!

**Comment by Folyd** [comment]
Hi @ear7h. Query.rs support query parameter, for example: https://query.rs/?q=vec
I also added opensearch, can you give it a try?

**Comment by niclashoyer** [comment]
Adding `https://query.rs/?q=%s` as bookmark in FF does work. Opensearch integration however, does not.

**Comment by niclashoyer** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/OpenSearch the changes of https://github.com/huhu/query.rs/commit/f26a5df39b32b80c0a21720130d54dfc773693ff should be sufficient 🤷🏽

**Comment by Folyd** [comment]
Yes, I just follow that docs to add opensearch, it should be work?

**Comment by vinaychandra** [comment]
I am able to add Query.rs to the search bar using the right click context menu in Firefox. Do you if an autocomplete API is possible? That way it pretty much replaces the original Rust Search extension without any extension being installed.

**Comment by Folyd** [comment]
Hi, @vinaychandra. How to trigger suggestion in Firefox address bar? I tried, but not working.

![image](https://github.com/user-attachments/assets/c8cb70dd-70ee-4eb7-b5c6-df70d650e5b6)

**Comment by vinaychandra** [comment]
Yes, I am also facing the same. This works when i am testing this locally. You can do this
- Update `vite dev` to include `--port 80` in package.json
- Update opensearch.xml to use `http://localtest.me` as url instead of query.rs. LocalTest is literally localhost dns
- Delete existing search extension in firefox and re-add it from the URL in http://localtest.me/
- Search using firefox.

Can you add some server side logs and check if firefox is calling them? Also, can you enable caching on top? May be that would improve the latency (am currently seeing ~550ms when calling the query.rs url)

**Comment by Folyd** [comment]
I checked the logs, Firefox did call the suggest api, but something Cloudflare raise [Worker exceed CPU time](https://community.cloudflare.com/t/streaming-response-catch-worker-exceeded-cpu-time-limit-error/372138/2) error, so I try to reduce the CPU time via [this commit](https://github.com/huhu/query.rs/commit/3a8c8bd068b221bb9a999aea01af816e79cc47ed). I also added cache rule, we'll hit the cache for subsequent requests.
<img width="522" alt="image" src="https://github.com/user-attachments/assets/1310a2fe-ed87-4828-b5d1-efccc5c5df11">

 However, the Firefox suggest still not working, I'm not sure why. 🥲

**Comment by vinaychandra** [comment]
I get the suggestions on my system working now. Try removing and re-adding the search engine. You might want to also try adding a space at the end although Not needed usually.

**Comment by vinaychandra** [comment]
@Folyd requesting to undo the removal of "std:" prefix for auto-redirection

**Comment by Folyd** [comment]
The opensearch suggest totally not working on my Firefox, even with https://localtest.me. I cannot test it right now. Any other browser support opensearch?

```
[
  'opt',
  [
    'std::option',
    'std::option::Option',
    'std::fs::options',
    'std::option_env',
    'test::Options',
    'test::options',
    'core::prelude::rust_2024::option_env',
    'std::os::unix::thread::into_pthread_t'
  ],
  [
    'Optional values.',
    'The <code>Option</code> type. See the module level documentation for …',
    'Returns a new OpenOptions object.',
    'Optionally inspects an environment variable at compile …',
    'Options for the test run defined by the caller (instead of …',
    '',
    '',
    'Consumes the thread, returning the raw pthread_t'
  ],
  [
    'https://doc.rust-lang.org/std/option/index.html',
    'https://doc.rust-lang.org/std/option/enum.Option.html',
    'https://doc.rust-lang.org/std/fs/struct.File.html#method.options',
    'https://doc.rust-lang.org/std/macro.option_env.html',
    'https://doc.rust-lang.org/test/struct.Options.html',
    'https://doc.rust-lang.org/test/struct.TestOpts.html#structfield.options',
    'https://doc.rust-lang.org/core/prelude/rust_2024/index.html#reexport.option_env',
    'https://doc.rust-lang.org/std/os/unix/thread/trait.JoinHandleExt.html#tymethod.into_pthread_t'
  ]
]
```
BTW, doesn't the Firefox suggestion use the url? I think it should, otherwise why the opensearch specifications need the url part?

**Comment by vinaychandra** [comment]
Make sure you use port 80/443. Otherwise it didn't work for me. 

Unfortunately only completions are supported. The urls and descriptions are not supported by any browser. They never implemented it and there are still open requests on firefox for it. 

This is pretty much the reason i use the redirect url along with the std prefix. To workaround this limitation. 

I was seeing the search suggestions even in edge yesterday. But in my observation, it is not always working for some reason. Some suggestions are getting triggered where as some times they aren't. Don't know why. I don't know how to debug unfortunately. There is no firefox tab that shows the outbound request for search suggestions.

**Comment by Folyd** [comment]
Ok, I see. I did use 80 port, it works on Edge, but not works on Firefox.  

I already undo it: https://github.com/huhu/query.rs/commit/78eab3a99a8b4dded56fb323ea44678626b72a1f

**Comment by vinaychandra** [comment]
I am able to make it consistently work in firefox. Go to `about:config`, add a config named `browser.search.suggest.timeout` (discovered from [here](https://searchfox.org/mozilla-central/source/toolkit/components/search/SearchSuggestionController.sys.mjs)) and set a value to something like `2000` for 2 seconds. The default is 500ms and looks like not enough. Also, ensure you remove and re-add the query.rs search engine to ensure firefox sees the suggest setting.


You can see the logs for suggest by using "Browser Console" and selecting XHR
![image](https://github.com/user-attachments/assets/3ea7df6c-517c-43b3-abc9-4614ea9123ef)

**Comment by Folyd** [comment]
Wow, thanks @vinaychandra. Change `browser.search.suggest.timeout` to 2000 make it works like a charm. 👍

**Comment by Folyd** [comment]
I wrote a blog post to introduce how to enable opensearch in Firefox and Edge: https://query.rs/opensearch
