### ISSUE TITLE
Choosing the "Remind:" result redirects to 404

### ISSUE THREAD

**Issue by stormofice** [huhu/query.rs#6]
When choosing the entry reminding users of the 20k crate indexing limitation:
![image](https://github.com/user-attachments/assets/3aacc0ae-0843-43f7-b8ad-c8a7a802857e)
one gets (re-)directed to https://query.rs/remind.

In my opinion this entry should either be:
- unclickable
- or redirect to a page/issue/... explaining the limitation

**Comment by Folyd** [comment]
Good catch! Thanks for the feedback, I fixed it.

**Comment by stormofice** [comment]
Thanks!
