### ISSUE TITLE
Feature request: support C-p/C-n to navigate query candidates

### ISSUE THREAD

**Issue by jiacai2050** [huhu/query.rs#8]

**Comment by Folyd** [comment]
Thanks, do you mean shortcut to page down/up?

**Comment by jiacai2050** [comment]
Yes.

**Comment by Folyd** [comment]
Resolved via https://github.com/huhu/query.rs/commit/2c2676662f2276b127de2bc19b5025572f3929e5

**Comment by jiacai2050** [comment]
I'm afraid this is not what I mean, `ctrl-n/p` is used to move up/down selection for pop-up search items, not paging.

**Comment by Folyd** [comment]
I think you can use arrow key ↑↓ to move up/down :)

**Comment by jiacai2050** [comment]
Arrow key works, but not very useful, since they are hard to type... at least for Emacs user.

We can easily type `Ctrl-N/P` without moving hands.

**Comment by Folyd** [comment]
How about `ctrl-j/k` to move down/up?

**Comment by Folyd** [comment]
Now query.rs support `ctrl-j/k` to move down/up, welcome to give it a try. 😄
