### ISSUE TITLE
Suggestion box skips item when using keyboard navigation

### ISSUE THREAD

**Issue by J-Cake** [huhu/query.rs#9]
Hey very cool! I just noticed that the suggestion box will skip every suggestion when navigating with keys.

**Comment by Folyd** [comment]
Hey, what do you mean skip every suggestion? Can you give some screenshots?

**Comment by J-Cake** [comment]
Hi, thanks for getting back to me, I can't reproduce the issue anymore, but on my work laptop, the suggestion box would always skip the 2nth item

**Comment by Folyd** [comment]
Ok, I know this bug, but it hard to reproduce indeed.
